services:
  - type: web
    name: todoList
    env: static
    buildCommand: npm install && npm run build && ls -la dist
    publishDirectory: dist
    nodeVersion: 20
    buildFilter:
      paths:
        - src/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: BUILD_PATH
        value: dist
