services:
  - type: web
    name: todoList
    env: static
    buildCommand: npm install && npm run build
    publishDirectory: dist
    buildFilter:
      paths:
        - src/**
    envVars:
      - key: NODE_ENV
        value: production
